name: Lint

on:
  push:
    branches: ["**"]

jobs:
  lint-and-fix:
    name: Lint and Fix
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Markdown lint and fix
        uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          globs: |
            "**/*.md"
          fix: true

      - name: Install pnpm via corepack
        run: corepack enable && corepack install

      - name: Set node LTS
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: pnpm

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Code Lint and Fix
        run: pnpm lint:fix

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: format and lint fix [skip ci]"
